// Generated by scripts/generate-thing-alpha-footprints.mjs.
export const THING_CURATED_COUNT = 12;
export const THING_CATALOG_COUNT = 3731;
export const THING_CATALOG_SOURCE_COMMIT = "8998f5dd683424a73e2314a8c1f1e359c19e8742";
